// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright 2025 Sony Group Corporation

package cmd

import (
	"fmt"
	"log/slog"
	"slices"

	"github.com/sony/niwashi/internal/logger"
	"github.com/sony/niwashi/internal/plan"
	"github.com/sony/niwashi/internal/workflow/applier"
	"github.com/spf13/cobra"
)

type ApplyData struct {
	Plan           string
	WorkDir        string
	RecipeDir      []string
	LogLines       uint
	Yes            bool
	DryRun         string
	LogConfig      logger.Config
	ProgressFormat string
	Prune          bool
	Destroy        bool
	Concurrency    uint
	StrictCheck    bool
}

var applyData ApplyData

func newApplyCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Apply an execution plan",
		Long: `Executes the actions defined in a generated plan file to update the
infrastructure. It runs tasks in the specified order to transition the
system from the initial state to the desired target state.`,
		SilenceUsage: true, // Don't show usage on error
		PreRunE: func(cmd *cobra.Command, args []string) error {
			// Check dry-run level
			if !slices.Contains(DryRunLevels, applyData.DryRun) {
				return fmt.Errorf("invalid dry-run level: %s", applyData.DryRun)
			}

			// Check concurrency number
			if applyData.Concurrency == 0 {
				return fmt.Errorf("concurrency must be greater than 0")
			}
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			err := RunApplyCmd(&applyData)
			if err != nil {
				return err
			}
			return nil
		},
	}

	cmd.Flags().StringArrayVar(&applyData.RecipeDir, FlagRecipeDir, DefaultRecipeDir, UsageRecipeDir)
	cmd.Flags().StringVar(&applyData.WorkDir, FlagWorkDir, DefaultWorkDir, UsageWorkDir)
	cmd.Flags().StringVar(&applyData.Plan, "plan", "", "Path to the plan file generated by nwsctl plan.")
	cmd.Flags().UintVar(&applyData.LogLines, "log-lines", 10, "Number of lines to show in live log. Can also be set with NWS_LOG_LINES env var.")
	cmd.Flags().BoolVar(&applyData.Yes, "yes", false, "Skip interactive confirmation before applying a destruction plan.")
	cmd.Flags().StringVar(&applyData.DryRun, "dry-run", DryRunOff, "Specify dry-run mode.")
	cmd.Flags().BoolVar(&applyData.Prune, "prune", false, "Apply prune plan.")
	cmd.Flags().BoolVar(&applyData.Destroy, "destroy", false, "Create a plan to destroy all resources.")
	cmd.Flags().UintVar(&applyData.Concurrency, "concurrency", applier.DefaultConcurrency, "Number of concurrent tasks to run.")
	cmd.Flags().BoolVar(&applyData.StrictCheck, "strict-check", false, "Enable strict check mode. In this mode, the nwsctl will perform recipe hash and plan hash validation before applying the plan. If the validation fails, the apply operation will be aborted. This is useful to prevent applying a plan that may be outdated or does not match the current recipes.")

	// todo: logging options

	// --progress=[tui|json|plain|auto]
	defaultProgress := "auto"
	cmd.Flags().StringVar(&applyData.ProgressFormat, "progress", defaultProgress, "Progress output format (tui, json, plain, auto).")

	// --log-file=[path|-]
	// --log-format=[plain|json]
	cmd.Flags().StringVar(&applyData.LogConfig.LogFile, "log-file", "", "Path to the log file. Use '-' for stdout.")
	cmd.Flags().StringVar(&applyData.LogConfig.LogFormat, "log-format", "plain", "Log format (plain or json).")

	if err := cmd.MarkFlagRequired("plan"); err != nil {
		panic(fmt.Sprintf("Failed to mark --plan flag as required: %v", err))
	}

	return cmd
}

func RunApplyCmd(arg *ApplyData) error {

	tui, err := initLogger(arg)
	if err != nil {
		return err
	}
	defer finalizeLogger(tui)

	logger.Info("ApplyStart", "plan", arg.Plan)

	cfg := applier.NewConfig()

	cfg.RecipeDirs = arg.RecipeDir
	cfg.WorkDir = arg.WorkDir
	cfg.PlanFile = arg.Plan
	cfg.DryRunMode = arg.DryRun
	cfg.DevOption = applier.NewDevOption(GetDevOptions())
	cfg.Concurrency = arg.Concurrency
	cfg.StrictCheck = arg.StrictCheck

	if arg.Destroy && arg.Prune {
		return fmt.Errorf("cannot specify both --destroy and --prune options")
	}

	if arg.Destroy {
		cfg.Mode = plan.ModeDestroy
	} else if arg.Prune {
		cfg.Mode = plan.ModePrune
	} else {
		cfg.Mode = plan.ModeDefault
	}

	applier, err := applier.NewApplier(cfg)
	if err != nil {
		return err
	}

	// todo: stop tui logger
	// ask for confirmation if it's a destroy plan and not in dry-run mode
	switch cfg.Mode {
	case plan.ModeDestroy, plan.ModePrune:
		if !arg.Yes && arg.DryRun == DryRunOff {
			tui.Pause()
			confirmed, err := askConfirmation(cfg)
			if err != nil {
				return err
			}
			if !confirmed {
				return nil
			}
			tui.Resume()
		}
	}

	err = applier.Apply()

	logger.Info("ApplyComplete", "plan", arg.Plan, "error", err)

	return err
}

func initLogger(arg *ApplyData) (*ApplyTui, error) {

	// Progress format:
	// - with dry-run: force to use plain format
	// - without dry-run: use specified format, default to auto (tui if terminal, otherwise plain)

	if arg.DryRun != "" && arg.DryRun != DryRunOff {
		logger.Info("DryRunModeEnabled", "mode", arg.DryRun)
		arg.ProgressFormat = "pretty"
	}

	handler, tui, err := BuildApplyLogger(arg.ProgressFormat)
	if err != nil {
		return nil, err
	}

	arg.LogConfig.BuildConsoleHandler = func() (slog.Handler, error) {
		return handler, nil
	}
	if err := logger.InitLogger(arg.LogConfig); err != nil {
		tui.Stop()
		return nil, err
	}

	return tui, nil
}

func finalizeLogger(tui *ApplyTui) {
	tui.Stop()
	logger.Finalize()
}

func askConfirmation(cfg *applier.Config) (bool, error) {
	var prompt string

	if cfg.Mode == plan.ModeDestroy {
		prompt = "This plan will destroy all resources. Are you sure you want to apply this plan?"
	} else {
		prompt = "This plan will prune resources. Are you sure you want to apply this plan?"
	}

	fmt.Print(prompt + " (y/N): ")

	var response string
	_, err := fmt.Scanln(&response)
	if err != nil {
		response = "N"
	}

	if response != "y" && response != "Y" {
		logger.Info("ApplyCancelled", "reason", "user declined to apply the plan")
		return false, nil
	}
	return true, nil
}
