// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright 2026 Sony Group Corporation

package applier

type DevOption struct {
	simCmd      bool
	patchPrefix string
}

var options = map[string]func(opt *DevOption, v string){
	"simCmd": func(opt *DevOption, _ string) {
		// This option simulates the exec.local specified in the recipe.
		// The command will not be actually executed.
		opt.simCmd = true
	},
	"patchPrefix": func(opt *DevOption, v string) {
		// This option allows saving the data generated by recipes or the system in JSON Patch format to a file.
		// In addition to this prefix, a sequential number is added to the file name when saving.
		// If you want to save including directories, the directories will not be created automatically if they do not exist.
		// example: "patchPrefix": "dev-"
		opt.patchPrefix = v
	},
}

func NewDevOption(kv map[string]string) *DevOption {
	opt := DevOption{}
	for k, v := range kv {
		if f, exist := options[k]; exist {
			f(&opt, v)
		}
	}
	return &opt
}

func (d *DevOption) SimCmd() bool {
	if d == nil {
		return false
	}
	return d.simCmd
}

func (d *DevOption) PatchPrefix() string {
	if d == nil {
		return ""
	}
	return d.patchPrefix
}
