---
services:
  cp: # See https://hub.docker.com/r/linuxserver/openssh-server
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: nws-cluster-cp
    hostname: nws-cluster-cp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY_FILE=/pubkey
      - USER_NAME=${SSH_USERNAME}
    volumes:
      - ${PWD}/${PRIVATE_KEY_PATH}.pub:/pubkey:ro
    ports:
      - ${CP_SSH_PORT}:2222
    restart: unless-stopped

  worker1: # See https://hub.docker.com/r/linuxserver/openssh-server
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: nws-cluster-worker1
    hostname: nws-cluster-worker1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY_FILE=/pubkey
      - USER_NAME=${SSH_USERNAME}
    volumes:
      - ${PWD}/${PRIVATE_KEY_PATH}.pub:/pubkey:ro
    ports:
      - ${WORKER_SSH_PORT}:2222
    restart: unless-stopped
